name: Update Function Branches

on:
  workflow_dispatch:

jobs:
  update-functions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install json5 tabulate

      - name: Process functions
        run: |
          python - << 'EOF'
import json5, os, subprocess
from tabulate import tabulate

if not os.path.exists("zenodo.json"):
    print("ERROR: zenodo.json not found!")
    exit(1)

with open("zenodo.json", "r") as f:
    data = json5.load(f)

dashboard = []

for idx, func in enumerate(data.get("workExample", []), 1):
    branch = f"func-{func['name'].replace(' ', '-').lower()}-v{idx}"
    subprocess.run(["git", "checkout", "-b", branch])
    os.makedirs("functions", exist_ok=True)
    filename = f"functions/{func['name'].replace(' ', '-').lower()}.json"
    json5.dump({"workExample": [func]}, open(filename, "w"), indent=2)
    subprocess.run(["git", "add", filename])
    subprocess.run(["git", "commit", "-m", f"Add function {func['name']} v{idx}"])
    subprocess.run(["git", "push", "-u", "origin", branch])
    dashboard.append({"Function": func["name"], "Branch": branch, "Version": idx})

os.makedirs("dashboard", exist_ok=True)
json5.dump(dashboard, open("dashboard/functions-dashboard.json", "w"), indent=2)
print(tabulate(dashboard, headers="keys", tablefmt="github"))
EOF

      - uses: actions/upload-artifact@v4
        with:
          name: functions-dashboard
          path: dashboard/functions-dashboard.json
