name: JSON Functions PR

on:
  push:
    branches:
      - main
  workflow_dispatch:   # erlaubt manuelles Starten

jobs:
  repair-json:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json5 tabulate

      # 4. Script ausführen
      - name: Run repair_json.py
        run: python scripts/repair_json.py

      # 5. Änderungen committen und PR erstellen
      - name: Commit & Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit_message: "Fail-Safe JSON Repair applied"
          branch: fail-safe-json-repair-dashboard
          title: "Fail-Safe JSON Repair"
          body: "Automated JSON repair applied via workflow."
          base: main
