name: Generate Functions PR

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  generate-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies"

      - name: Generate Python modules from zenodo.json
        run: python scripts/generate_functions.py

      - name: Commit generated modules
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate Python modules from zenodo.json"
          branch: fail-safe-json-repair-dashboard
          push: true
