name: JSON Functions PR

on:
  push:
    branches:
      - main
  workflow_dispatch:   # manuell starten

jobs:
  repair-json:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Python-Umgebung einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json5 tabulate PyGithub

      # 4️⃣ JSON-Reparatur ausführen
      - name: Run repair_json.py
        run: python scripts/repair_json.py

      # 5️⃣ Änderungen committen & Pull Request erstellen
      - name: Commit & Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: fail-safe-json-repair-dashboard
          base: main
          title: "Fail-Safe JSON Repair"
          body: "Automated JSON repair applied via workflow."
          commit-message: "Fail-Safe JSON Repair applied"
          labels: |
            automated
            json-repair
