name: JSON Functions PR

on:
  push:
    branches:
      - main
      - 'feature/**'  # Optional: für alle Feature-Branches

jobs:
  generate-functions:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json5

      # 4. JSON Repair Script ausführen
      - name: Run JSON repair
        run: python scripts/repair_json.py

      # 5. Änderungen committen und neuen PR vorbereiten
      - name: Create Pull Request with updated JSON
        uses: peter-evans/create-pull-request@v5
        with:
          commit_message: "Fail-Safe JSON Repair applied"
          branch: fail-safe-json-repair-dashboard
          title: "Fail-Safe JSON Repair applied"
          body: "Automated repair of JSON functions from Zenodo to Git branches."
          push: true
