name: Fail-Safe JSON Repair

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  json-repair:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Python einrichten
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # kannst du auf 3.11 ändern, wenn nötig

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json5 PyGithub tabulate

      # 4️⃣ JSON-Reparatur Script ausführen
      - name: Run JSON Repair Script
        run: python scripts/repair_json.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
