name: Sync metadata.json to branches

on:
  push:
    paths:
      - 'metadata.json'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync metadata.json to other branches
        run: |
          branches=("dev" "release")  # Hier alle anderen Branches eintragen
          for branch in "${branches[@]}"; do
            git fetch origin $branch
            git checkout $branch
            cp ../metadata.json ./metadata.json || true  # aus übergeordnetem Verzeichnis holen
            git add metadata.json
            git diff-index --quiet HEAD || git commit -m "Sync metadata.json from main"
            git push origin $branch
          done
